[package]
name = "dogwood-py-native"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "dogwood_py_native"
crate-type = ["cdylib"]

[dependencies]
dogwood-language = { package = "amzn-dogwood-language", git = "https://github.com/dogwood-policy/dogwood.git" }
pyo3 = { version = "0.22", features = ["abi3-py310"] }
serde_json = "1"
